### ISSUE TITLE
Erro in timeslot view (0.90+1.3)

### ISSUE THREAD

**Issue by tsmr** [fusioninventory/fusioninventory-for-glpi#1867]
![image](https://cloud.githubusercontent.com/assets/13178158/16187611/99ecd126-36d1-11e6-8695-14212fab8a59.png)

```
2016-06-20 10:22:56 [6@GLPI]
  *** PHP Warning(2): Cannot modify header information - headers already sent by (output started at /usr/share/glpi/inc/dropdown.class.php:1825)
  Backtrace :
  :                                                  
  inc/html.class.php:2401                            header()
  inc/html.class.php:1037                            Html::header_nocache()
  inc/html.class.php:1243                            Html::includeHeader()
  inc/html.class.php:781                             Html::header()
  inc/html.class.php:541                             Html::displayErrorAndDie()
  inc/commondbtm.class.php:2447                      Html::displayRightError()
  inc/commondbtm.class.php:2131                      CommonDBTM->check()
  ...fusioninventory/inc/timeslotentry.class.php:167 CommonDBTM->initForm()
  ...fusioninventory/inc/timeslotentry.class.php:147 PluginFusioninventoryTimeslotEntry->formDeleteEntry()
  plugins/fusioninventory/inc/timeslot.class.php:239 PluginFusioninventoryTimeslotEntry->formEntry()
  inc/commonglpi.class.php:464                       PluginFusioninventoryTimeslot->showForm()
  ajax/common.tabs.php:93                            CommonGLPI::displayStandardTab()
```

**Comment by tsmr** [comment]
resolved with comment $this->initForm(key($dbentries), $options); into timeslotentry.class.php l167

**Comment by ddurieux** [comment]
Seems you haven't right on the timeslot :p

**Comment by tsmr** [comment]
All is checked in my profile (super-admin)

**Comment by pVesian** [comment]
This is still happening on 9.1+1.1: https://github.com/fusioninventory/fusioninventory-for-glpi/issues/1695#issuecomment-273076365

**Comment by ddurieux** [comment]
this version is no longer supported
