### ISSUE TITLE
Global Rules does not work for Dynamic Groups

### ISSUE THREAD

**Issue by eduardomozart** [fusioninventory/fusioninventory-for-glpi#3101]
GLPI version: 9.5.4
FusionInventory for GLPI version: FusionInventory 9.5.0+2.0

When trying to create a Collect task following the official instructions (https://fusioninventory.org/documentation/tasks/collect.html), the following happens.

Expectative:

![Capture09](https://user-images.githubusercontent.com/2974895/109179127-57e71c00-7768-11eb-82a3-6ea5ff0911e7.png)

Reality:

**AFTER** upgrading FusionInventory for GLPI plug-in from 9.5.0+1.0 to 9.5.0+2.0, only the Network Port menu is shown when selecting Global Rules:

![screenshot](https://user-images.githubusercontent.com/2974895/110043075-8a26e980-7d25-11eb-94f8-65e8986dc039.png)

**BEFORE** upgrading FusionInventory for GLPI plug-in from 9.5.0+1.0 to 9.5.0+2.0, all Global Rules submenus were shown, including Software, but no dropdown was being shown, as screenshot below:

![2021-02-25 12_42_51-Window](https://user-images.githubusercontent.com/2974895/109179139-5a497600-7768-11eb-982e-fd33dbcfa48e.png)

No error is thrown into any logs into ``<GLPI_ROOT>/files/_log`` folder and into Apache ``errors.log`` and ``access.log``.

```
[code]
 
GLPI 9.5.4 ( => /var/www/clients/client0/web1/web)
Installation mode: TARBALL

Server
 
Operating system: Linux ispconfig.example.com 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Mon Jan 18 17:05:51 UTC 2021 x86_64
PHP 7.2.34 fpm-fcgi (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mcrypt,
	mysql, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, snmp, soap, sockets, sodium, sqlite3,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="150 M" safe_mode="" session.save_handler="files"
	upload_max_filesize="150M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.3.27-MariaDB
	Server SQL Mode: 
	Parameters: c0glpiuser@localhost/c0glpi
	Host info: Localhost via UNIX socket
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
CAS extension is installedCAS extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.3.27) - Perfect!Database version seems correct (10.3.27) - Perfect!
Timezones seems loaded in databaseTimezones seems loaded in database
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/clients/client0/web1/web/files/_cache has been validated.Write access to /var/www/clients/client0/web1/web/files/_cache has been validated.
Write access to /var/www/clients/client0/web1/web/config has been validated.Write access to /var/www/clients/client0/web1/web/config has been validated.
Write access to /var/www/clients/client0/web1/web/files/_cron has been validated.Write access to /var/www/clients/client0/web1/web/files/_cron has been validated.
Write access to /var/www/clients/client0/web1/web/files has been validated.Write access to /var/www/clients/client0/web1/web/files has been validated.
Write access to /var/www/clients/client0/web1/web/files/_dumps has been validated.Write access to /var/www/clients/client0/web1/web/files/_dumps has been validated.
Write access to /var/www/clients/client0/web1/web/files/_graphs has been validated.Write access to /var/www/clients/client0/web1/web/files/_graphs has been validated.
Write access to /var/www/clients/client0/web1/web/files/_lock has been validated.Write access to /var/www/clients/client0/web1/web/files/_lock has been validated.
Write access to /var/www/clients/client0/web1/web/files/_pictures has been validated.Write access to /var/www/clients/client0/web1/web/files/_pictures has been validated.
Write access to /var/www/clients/client0/web1/web/files/_plugins has been validated.Write access to /var/www/clients/client0/web1/web/files/_plugins has been validated.
Write access to /var/www/clients/client0/web1/web/files/_rss has been validated.Write access to /var/www/clients/client0/web1/web/files/_rss has been validated.
Write access to /var/www/clients/client0/web1/web/files/_sessions has been validated.Write access to /var/www/clients/client0/web1/web/files/_sessions has been validated.
Write access to /var/www/clients/client0/web1/web/files/_tmp has been validated.Write access to /var/www/clients/client0/web1/web/files/_tmp has been validated.
Write access to /var/www/clients/client0/web1/web/files/_uploads has been validated.Write access to /var/www/clients/client0/web1/web/files/_uploads has been validated.
Write access to /var/www/clients/client0/web1/web/marketplace has been validated.Write access to /var/www/clients/client0/web1/web/marketplace has been validated.
Web access to files directory is protectedWeb access to files directory is protected
For security reasons, SELinux mode should be Enforcing.For security reasons, SELinux mode should be Enforcing.

GLPI constants
 
GLPI_ROOT: /var/www/clients/client0/web1/web
GLPI_CONFIG_DIR: /var/www/clients/client0/web1/web/config
GLPI_VAR_DIR: /var/www/clients/client0/web1/web/files
GLPI_MARKETPLACE_DIR: /var/www/clients/client0/web1/web/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_FORCE_EMPTY_SQL_MODE: 1
GLPI_DOC_DIR: /var/www/clients/client0/web1/web/files
GLPI_CACHE_DIR: /var/www/clients/client0/web1/web/files/_cache
GLPI_CRON_DIR: /var/www/clients/client0/web1/web/files/_cron
GLPI_DUMP_DIR: /var/www/clients/client0/web1/web/files/_dumps
GLPI_GRAPH_DIR: /var/www/clients/client0/web1/web/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/clients/client0/web1/web/files/_locales
GLPI_LOCK_DIR: /var/www/clients/client0/web1/web/files/_lock
GLPI_LOG_DIR: /var/www/clients/client0/web1/web/files/_log
GLPI_PICTURE_DIR: /var/www/clients/client0/web1/web/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/clients/client0/web1/web/files/_plugins
GLPI_RSS_DIR: /var/www/clients/client0/web1/web/files/_rss
GLPI_SESSION_DIR: /var/www/clients/client0/web1/web/files/_sessions
GLPI_TMP_DIR: /var/www/clients/client0/web1/web/files/_tmp
GLPI_UPLOAD_DIR: /var/www/clients/client0/web1/web/files/_uploads
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/clients/client0/web1/web/locales
GLPI_VERSION: 9.5.4
GLPI_SCHEMA_VERSION: 9.5.4
GLPI_MIN_PHP: 7.2.0
GLPI_YEAR: 2021

Libraries
 
htmlawed/htmlawed version 1.2.5 in (/var/www/clients/client0/web1/web/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.1.6 in (/var/www/clients/client0/web1/web/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.6 in (/var/www/clients/client0/web1/web/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.3.5 in (/var/www/clients/client0/web1/web/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/clients/client0/web1/web/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/clients/client0/web1/web/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/clients/client0/web1/web/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/clients/client0/web1/web/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/clients/client0/web1/web/vendor/sabre/http/lib)
sabre/uri in (/var/www/clients/client0/web1/web/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/clients/client0/web1/web/vendor/sabre/vobject/lib)
laminas/laminas-cache in (/var/www/clients/client0/web1/web/vendor/laminas/laminas-cache/src)
laminas/laminas-i18n in (/var/www/clients/client0/web1/web/vendor/laminas/laminas-i18n/src)
laminas/laminas-serializer in (/var/www/clients/client0/web1/web/vendor/laminas/laminas-serializer/src)
monolog/monolog in (/var/www/clients/client0/web1/web/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/clients/client0/web1/web/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/clients/client0/web1/web/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/clients/client0/web1/web/vendor/symfony/console)
scssphp/scssphp in (/var/www/clients/client0/web1/web/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/clients/client0/web1/web/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/clients/client0/web1/web/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/clients/client0/web1/web/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/clients/client0/web1/web/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/clients/client0/web1/web/vendor/ramsey/uuid/src)
psr/log in (/var/www/clients/client0/web1/web/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/clients/client0/web1/web/vendor/psr/simple-cache/src)
mexitek/phpcolors in (/var/www/clients/client0/web1/web/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/clients/client0/web1/web/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/clients/client0/web1/web/vendor/guzzlehttp/psr7/src)
wapmorgan/unified-archive in (/var/www/clients/client0/web1/web/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/clients/client0/web1/web/vendor/paragonie/sodium_compat/src)
phpCas version 1.3.8 in (/usr/share/pear)

LDAP directories
 
Server: 'ldaps://example.com', Port: '389', BaseDN: 'OU=example,DC=example,DC=com,DC=br', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(!(memberOf=CN=Contas de Serviço -
		Negar Logon Interativo,OU=Serviços,OU=TI,OU=São
		Leopoldo,OU=example,DC=example,DC=com,DC=br))(!(sAMAccountName=fabrica))(!(sAMAccountName=cq))(!(sAMAccountName=manutencao)))',
		RootDN: 'glpiaduser@example.com', Use TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP+SSL (glpi@example.com@smtp.kinghost.net)

Mails receivers
 
Name: 'glpi@example.com' Active: Yes
	Server: '{smtp.kinghost.net:995/pop/ssl/validate-cert}' Login: 'glpi@example.com' Password: Yes

Plugins list
 
	fields               Name: Campos adicionais              Version: 1.12.2     State: Enabled
	behaviors            Name: Comportamentos                 Version: 2.4.1      State: Enabled
	accounts             Name: Contas                         Version: 2.6.0      State: Enabled
	archimap             Name: Diagrams                       Version: 2.2.1      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.5+2.0  State: Enabled
	genericobject        Name: Gerenciamento de objetos       Version: 2.10.0     State: Installed / not activated
	manufacturersimports Name: Importação de fornecedores     Version: 2.3.1      State: Enabled
	pdf                  Name: Imprimir em PDF                Version: 1.7.0      State: Enabled
	mreporting           Name: Mais Relatórios                Version: 1.7.1      State: Enabled
	printercounters      Name: Printer counters               Version: 1.7.0      State: Enabled
	reports              Name: Relatórios                     Version: 1.14.0     State: Enabled
	taskdrop             Name: TaskDrop                       Version: 1.2.0      State: Enabled

[/code]
```

**Comment by ddurieux** [comment]
Seems a bug yes, will check it in couple of days, finish make tests up before ;)

**Comment by ddurieux** [comment]
I have checked, I have right the search 

![image](https://user-images.githubusercontent.com/239744/109803487-65e1e480-7c21-11eb-8388-b3fdd674f3b6.png)

**Comment by eduardomozart** [comment]
Hello, I did upgrade the GLPI to version 9.5.4 and FusionInventory for GLPI plug-in from version 9.5.0+1.0 to 9.5.0+2.0. I did a clean install from FusionInventory for GLPI plug-in, but the issue still persists. I did upgrade this issue description to describe my updated environment.

**Comment by ppenin** [comment]
Same issue for me with GLPI 9.5.4  & FusionInventory 9.5.0+1.0.
This problem and this one #3114 seem to come from GLPI version 9.5.4
It's a big regression. Help !

**Comment by ddurieux** [comment]
But unable to reproduce this problem, it's worked nicely on my computer :(

**Comment by ppenin** [comment]
In debug mode with a specific dynamic group that worked perfectly with GLPI 9.5.2 and FI 9.5.0.+1.0 but no more with
GLPI 9.5.4 and FI 9.5.0.+1.0 or GLPI 9.5.4 and FI 9.5.0.+2.0

![image](https://user-images.githubusercontent.com/22499638/110652897-12413f00-81bd-11eb-98b3-f0b141b52396.png)

**Comment by ddurieux** [comment]
it;s normal you don't have the 'Software' in the line 3 of the search (it's empty) ?

**Comment by ppenin** [comment]
Sure. It's empty because only Network port is choosable and software is not.
![image](https://user-images.githubusercontent.com/22499638/110658813-4e2ad300-81c2-11eb-9c95-39246b11fd17.png)

**Comment by ddurieux** [comment]
There is no `Network port` in the default list

![image](https://user-images.githubusercontent.com/239744/110660086-81219680-81c3-11eb-9908-4142a6d3e919.png)

**Comment by ppenin** [comment]
we are at least 2 to encounter the problem
![image](https://user-images.githubusercontent.com/22499638/110660498-ebd2d200-81c3-11eb-9a29-5620ba08f89b.png)

**Comment by ppenin** [comment]
But global rules is ok whitin Software menu. 
![image](https://user-images.githubusercontent.com/22499638/110660695-1886e980-81c4-11eb-93b8-87fc66c0e11e.png)

**Comment by ddurieux** [comment]
Can you paste the plugins you use?

**Comment by ppenin** [comment]
yes but i tried to disable all plugins and same problem.

Plugins list
 
	barcode              Name: Barcode                        Version: 2.5.0      State: Enabled
	fields               Name: Champs supplémentaires         Version: 1.12.2     State: Installed / not activated
	timelineticket       Name: Chronologie des tickets        Version: 9.4+1.0    State: Installed / not activated
	behaviors            Name: Comportements                  Version: 2.4.1      State: Enabled
	datainjection        Name: Data Injection                 Version: 2.9.0      State: Enabled
	escalade             Name: Escalades                      Version: 2.6.1      State: Enabled
	dataflows            Name: Flux de données                Version: 2.2.2      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled
	flyvemdm             Name: Gestion d'appareil mobile Flyv Version: 2.0.0      State: Not installed
	pdf                  Name: Impression pdf                 Version: 1.7.0      State: Enabled
	mailanalyzer         Name: Mail Analyzer                  Version: 2.0.1      State: Enabled
	moreticket           Name: More ticket                    Version: 1.6.0      State: Enabled
	ocsinventoryng       Name: OCS Inventory NG               Version: 1.7.3      State: Installed / not activated
	mreporting           Name: Plus de rapports               Version: 1.7.2      State: Enabled
	reports              Name: Rapports                       Version: 1.14.0     State: Enabled
	dporegister          Name: Registre DPO                   Version: 1.4        State: Installed / not activated
	karastock            Name: Stock & Orders Management (Kar Version: 1.0        State: Enabled
	archisw              Name: Structures d'Applications      Version: 2.2.4      State: Enabled
	dashboard            Name: Tableau de bord                Version: 1.0.2      State: Enabled

**Comment by ddurieux** [comment]
disabled all + logout + login GLPI ?

**Comment by ppenin** [comment]
done. All plugins disabled but FusionInventory.
 I used another browser in order not to have cache issues : same problem ==> only Network port in dropdown list

This could help
![image](https://user-images.githubusercontent.com/22499638/110662726-102fae00-81c6-11eb-922a-a3207543b833.png)

**Comment by ddurieux** [comment]
I will read the code, perhaps I could sse something, but without have the problem, it's really difficult

**Comment by ppenin** [comment]
When i try to select an item (only network port available), i get a http 500 error
i'm not developer but it could help

![image](https://user-images.githubusercontent.com/22499638/110663692-f6db3180-81c6-11eb-9e70-4dab6b3e086a.png)

**Comment by ppenin** [comment]
Differences between /glpi/ajax/search.php in GLPI 9.5.4 (left) and 9.5.2 (right)
![image](https://user-images.githubusercontent.com/22499638/110664438-af08da00-81c7-11eb-8434-57b931ee6d11.png)

**Comment by eduardomozart** [comment]
The only plug-ins that I could find in common with @ppenin is "fields", "behaviors", "pdf", "mreporting" and "reports".
I tried to erase all ``glpi_plugin_fusioninventory*`` tables and start over but the issue still persists.

@ddurieux, I believe the issue is happening because of some of these plug-ins or because some code change into GLPI 9.5.4. You may reproduce this issue by creating a test GLPI environment with GLPI 9.5.3 and upgrading it with those plug-ins enabled to GLPI 9.5.4.

**Comment by ddurieux** [comment]
Ok, I'm on 9.5.3, I will test with 9.5.4 ;)

**Comment by ppenin** [comment]
We didn't update from 9.5.2 to 9.5.3 but directly to 9.5.4 because of a mailgate issue only solved in 9.5.4

**Comment by eduardomozart** [comment]
I had this issue into the Global Rules field into 9.5.3, I did upgraded to GLPI 9.5.4 in hope to fix this issue, but it get even worse. Anyway, hopes that @ddurieux can reproduce this issue, somehow I'm happy that I'm not the only one having this issue, so it can motivates the main contributors of FusionInventory team take a look at this issue.

**Comment by ddurieux** [comment]
It's the case, I took a look at this issue ^_^

**Comment by ppenin** [comment]
yes please because we are not able to deploy softwares with this issue and with #3114 / #3116

**Comment by ddurieux** [comment]
So many parts broken :(

**Comment by ddurieux** [comment]
Good news, I have the problem in 9.5.4
Now see why!

**Comment by is0x** [comment]
hi, i have the same problems as ppenin with version 9.5.4 and fusioninventory #3114 / #3116 . Thanks ddurieux for the effort we look forward to the solution :)

**Comment by ddurieux** [comment]
I see the problem, always a pleasure to discover an internal API modification on a minor version :rage:

**Comment by is0x** [comment]
ok XD, ddurieux will we have a version shortly?

**Comment by ddurieux** [comment]
A search engine function has been changed and before it was dynamic and works, now itemtype list is static so unable to works for fusioninventory.
Continue to search a solution, but I'm afraid I will need recode a big par of search into FusionInventory

**Comment by is0x** [comment]
and the part of deploy that does not get the package tab fusioninventory #3114

**Comment by ddurieux** [comment]
One problem after another

**Comment by ddurieux** [comment]
Seems found a solution, but need to test the criteria in the deploygroup and in the task with recalculation of the item of group.
Check it tomorow, I'm tired and pissed

**Comment by eduardomozart** [comment]
Hello @ddurieux, thank you for your hard work!
If you need someone to test the code, I can apply the fixes and provide feedback about it, maybe even help you to fix the code.

**Comment by ddurieux** [comment]
Ok, you can try and test with this fix when I will sleep: https://github.com/ddurieux/fusioninventory-for-glpi/commit/bb5cb9d7672cefe18f39244ea88fd715040c85b9

**Comment by ppenin** [comment]
I tried the fix.
In an dynamic group created in 9.5.2 version :
![image](https://user-images.githubusercontent.com/22499638/110708397-e93f9f00-81fa-11eb-8a9c-eb65564e93a7.png)

In a new dynamic group : 
the dropdown list seems to be ok but there are still errors and the request returns nothing

![image](https://user-images.githubusercontent.com/22499638/110708633-4176a100-81fb-11eb-9ebd-e15f5173922f.png)

About package action tab, nothing changed.
we keep hope

**Comment by ddurieux** [comment]
Yes, I saw the errors too.
So I continue to debug this :p

**Comment by ddurieux** [comment]
I have a hack for dynamic and seems working but not for static group.
Try to find another solution to works for both

**Comment by eduardomozart** [comment]
Hello @ddurieux,
Now the dropdown is showing correctly, but now I'm receiving the same SQL error from @ppenin:

```
Unknown column 'glpi_softwares.name' in 'field list' in query "SELECT DISTINCT `glpi_computers`.`id` AS id, 'eduardo.mozart' AS currentuser, `glpi_computers`.`entities_id`, `glpi_computers`.`is_recursive`, `glpi_computers`.`name` AS `ITEM_PluginFusioninventoryComputer_1`, `glpi_computers`.`id` AS `ITEM_PluginFusioninventoryComputer_1_id`, `glpi_entities`.`completename` AS `ITEM_PluginFusioninventoryComputer_80`, GROUP_CONCAT(DISTINCT CONCAT(`glpi_softwares`.`name`, '$#$' , `glpi_softwares`.`id`) ORDER BY `glpi_softwares`.`id` SEPARATOR '$$##$$') AS `ITEM_Software_1` FROM `glpi_computers`LEFT JOIN `glpi_entities` ON (`glpi_computers`.`entities_id` = `glpi_entities`.`id` ) WHERE `glpi_computers`.`is_deleted` = 0 AND `glpi_computers`.`is_template` = 0 AND ( (`glpi_softwares`.`name` LIKE '%Firefox%' ) ) GROUP BY `glpi_computers`.`id` ORDER BY `ITEM_PluginFusioninventoryComputer_1` ASC "
```

I believe it's happening because there's no "FROM `glpi_software`" clause, there's only "FROM `glpi_computer`" clause. Can you share your hack for dynamic queries so maybe help you can figure out why it's throwing an error? Actually, with FusionInventory for GLPI 9.5.0+2.0 and the @bb5cb9d commit, the Static Group search isn't working neither for Global search with the same ``Unknown column 'glpi_softwares.name' in 'field list'`` error.

**Comment by ddurieux** [comment]
Yes I know, there is many problem yet to fix about the search engine.
I test some fixes but not have found for the moment.

**Comment by ddurieux** [comment]
I'm near have a stable and useful solution, need finish and test it

**Comment by eduardomozart** [comment]
It's great! Please let us know if you need testers =)

**Comment by ppenin** [comment]
Hello @ddurieux, we believe in and are confident. We know we know it's hard work.
GLPI teams don't give you any help ?

**Comment by ddurieux** [comment]
I have pushed on a branch, you can test it: https://github.com/ddurieux/fusioninventory-for-glpi/commit/271de5d3c176eb775fb0d5604b22a5b940bc3f6e

I will do some manual tests before merge, like recalculate groups in tasks to be sure this part is ok (because many others parts are too broken).

**Comment by ddurieux** [comment]
> Hello @ddurieux, we believe in and are confident. We know we know it's hard work.
> GLPI teams don't give you any help ?

You mean the same persons have push code 'major changes' in a minor version? no thank you, I prefer will fix myself

**Comment by ppenin** [comment]
We agree with 9.5.4 wich looks like 9.6.0 ...
We need to update from 9.5.0+1.0 to 9.5.0+2.0 before fixing ?

**Comment by ddurieux** [comment]
If you are in 9.5.4, yes, because have security fix.
After you will need patch with this too: https://github.com/fusioninventory/fusioninventory-for-glpi/pull/3110/files

I think the others problems will be fixed this week end and I plan to release begin of next week

**Comment by eduardomozart** [comment]
Hello @ddurieux, I applied the commit @271de5d at FusionInventory for GLPI 9.5.0+2.0 and GLPI 9.5.4 and the computer groups (static and dynamic) worked as expected! Thank you! =)
I believe the next priority issue to fix is #3114

**Comment by ppenin** [comment]
fix are applied and it works for dynamic groups 👍 
Great job !
However, I noticed this warning. don't know if it is important or not.
![image](https://user-images.githubusercontent.com/22499638/110976988-e0b5a880-8361-11eb-9fc5-1c409eb70d95.png)

**Comment by ddurieux** [comment]
It's because you not update with the rigth procedure, follow the link in the warning

**Comment by ppenin** [comment]
it's ok now. Never did so to update FI plugin. I will remember for next time

**Comment by ddurieux** [comment]
I have tested tasks, and it's ok ;)

**Comment by eduardomozart** [comment]
@ddurieux, one thing that I forgot to say is that seems that the dropdown text was changed from "Add" to another one, so now this string isn't translated anymore. I believe that's now is necessary to update the translation and generate a new glpi.pot file, but I believe it's a standard process when releasing a new version of the plugin.

**Comment by cedric-anne** [comment]
> > Hello @ddurieux, we believe in and are confident. We know we know it's hard work.
> > GLPI teams don't give you any help ?
> 
> You mean the same persons have push code 'major changes' in a minor version? no thank you, I prefer will fix myself

@ddurieux 

Have you at least considered that the disappearance of elements available in global rules related to classes extending an object from the core of GLPI could be an unintended side effect?
If you had reported this problem to us, we would have, after investigation, indicated to you that it was a bug, and that we should and would fix it in GLPI as soon as possible.
Instead, you have spent some time trying to get a fix that, at best, will not help, and at worst, will generate more bugs.

See https://github.com/glpi-project/glpi/pull/8833 for the fix.

Regards

**Comment by ddurieux** [comment]
The problem is that you have modified the behavior of a function and deprecated another in a 'minor version' instead do it in a major version. The mismanagement of the code not really from my side....

**Comment by eduardomozart** [comment]
Hello @cedric-anne and @ddurieux,

I did tried to undo the changes from #3121 and applied the changes from [glpi-project/glpi#8833](https://github.com/glpi-project/glpi/pull/8833) instead but it didn't work. I had to reapply the #3121 to make it work. I'd noticed that this problem started when upgrading to GLPI 9.5.3 and FusionInventory for GLPI 9.5.0+1.0.
